version: "3"
x-pod-settings: &pod-settings
  hostname: singularity

services:
  ollama:
    <<: *pod-settings
    image: ollama/ollama:rocm
    container_name: ollama
    devices:
      - /dev/kfd
      - /dev/dri
    volumes:
      - ${OLLAMA_VOLUME}:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    labels:
      - "io.containers.autoupdate=image"
    networks:
      - singularity_net

  open-webui:
    <<: *pod-settings
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - ${OPEN_WEBUI_VOLUME}:/app/backend/data
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    restart: unless-stopped
    labels:
      - "io.containers.autoupdate=image"
    networks:
      - singularity_net

  sillytavern:
    <<: *pod-settings
    image: ghcr.io/sillytavern/sillytavern:latest
    container_name: sillytavern
    environment:
      - TZ=America/Denver
    ports:
      - "8000:8000"
    volumes:
      - ${SILLYTAVERN_PLUGINS_VOLUME}:/home/node/app/plugins
      - ${SILLYTAVERN_CONFIG_VOLUME}:/home/node/app/config
      - ${SILLYTAVERN_DATA_VOLUME}:/home/node/app/data
    restart: unless-stopped
    labels:
      - "io.containers.autoupdate=image"
    networks:
      - singularity_net

  a1111:
    <<: *pod-settings
    image: rocm/pytorch:latest
    container_name: a1111
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video
    ipc: host
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    volumes:
      - ${A1111_VOLUME}:/dockerx
    ports:
      - "7860:7860"
    command: >
      bash -c "
      cd /dockerx &&
      if [ ! -d 'stable-diffusion-webui' ]; then
        git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui &&
        cd stable-diffusion-webui &&
        python -m pip install --upgrade pip wheel
      else
        cd stable-diffusion-webui &&
        git pull
      fi &&
      pip install -r requirements.txt &&
      pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/rocm5.4.2 &&
      REQS_FILE='requirements.txt' python launch.py --precision full --no-half --listen"
    restart: unless-stopped
    networks:
      - singularity_net

  comfyui:
    image: captainasic/comfyui-red
    container_name: comfyui-red
    ports:
      - "8188:8188"
    volumes:
      - ${COMFYUI_CONFIG_VOLUME}:/app/config
      - ${COMFYUI_MODELS_VOLUME}:/app/models
      - ${COMFYUI_OUTPUT_VOLUME}:/app/output
      - ${COMFYUI_CUSTOM_NODES_VOLUME}:/app/custom_nodes
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    group_add:
      - video
    command: ["--listen", "0.0.0.0", "--port", "8188"]
    restart: unless-stopped
    networks:
      - singularity_net

networks:
  singularity_net:
    driver: bridge

#oobabooga
#kohyaSS