version: "3"

x-pod-settings: &pod-settings
  hostname: singularity

services:
  ollama:
    <<: *pod-settings
    image: ollama/ollama:rocm
    container_name: ollama
    devices:
      - /dev/kfd
      - /dev/dri
    volumes:
      - /run/media/asic/Data/Singularity/pods/ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    labels:
      - "io.containers.autoupdate=image"
    networks:
      - singularity_net

  open-webui:
    <<: *pod-settings
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - /run/media/asic/Data/Singularity/pods/open-webui:/app/backend/data
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    restart: unless-stopped
    labels:
      - "io.containers.autoupdate=image"
    networks:
      - singularity_net

networks:
  singularity_net:
    driver: bridge
    
#A111
#ComfyUI
#oobabooga
#sillytavern
#tavernAI
#kohyaSS